version: '3.8'

services:
  telegram:
    build:
      context: .
      dockerfile: ./telegram/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    environment:
      - SIMULATION_CORE_HOST=http://multiagents_core:8001
    depends_on:
      - multiagents_core
    command: ["python", "main.py"]

  multiagents_core:
    build:
      context: .
      dockerfile: ./multiagents_core/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug"]
