version: '3.8'

services:
  telegram:
    build:
      context: .
      dockerfile: ./telegram/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    command: ["python", "main.py"]
