@startuml architecture_0.1.0
title "Архитектура тренажера переговоров"

actor "User" #green

("Telegram-bot") #LightBlue

"User" <--> ("Telegram-bot") : "Запросы и ответы:\n1) список кейсов\n2) выбор кейса\n3) предложение сделки агенту"
("Telegram-bot") <-[#LightBlue]-> "Regulator" : "1) предложение/ответ на сделки агенту\n2) выбор кейса"
"Cases Database" -[#Orange]-> ("Telegram-bot") : "список кейсов"

node "Multiagent Framework" {
    actor "Agent1" #Yellow
    actor "Agent2" #Yellow

    node "Regulator" #Purple {
        "Agent1" <--> "Regulator" : "Ответы или запросы на сделку\nдля User или других агентов"
        "Agent2" <--> "Regulator" : "Ответы или запросы на сделку\nдля User или других агентов"
    }
    
    node "Cases Database" #Orange {
        "Cases Database" -[#Orange]-> "Agent1" : "Данные кейсов"
        "Cases Database" -[#Orange]-> "Agent2" : "Данные кейсов"
    }
}

@enduml
